### ISSUE TITLE
Need help for tension Node

### ISSUE THREAD

**Issue by satcar77** [rashxl/myWorks#1]
Hello, I am quite a newbie in Node Editor stuffs. I compiled your tension node plugin, but couldn't figure out how to use it. Can you please provide me a screenshot of the Node Editor configuration using the tension node on a basic poly sphere?
![image](https://user-images.githubusercontent.com/7219502/111602135-27405280-87fb-11eb-8d63-dffca7c614a9.png)

**Comment by rashxl** [comment]
Hello, Satkar Dhakal
You should connect deformed meh to attr «in mesh» on a tension node and orig mesh to attr «res mesh» and at the end connect attr «out mesh» from node to new mesh to calculate tension node. I hope I explained it clearly to you.
Good luck! 
>Четверг, 18 марта 2021, 12:19 +03:00 от Satkar Dhakal ***@***.***>:
> 
> 
>Hello, I am quite a newbie in Node Editor stuffs. I compiled your tension node plugin, but couldn't figure out how to use it. Can you please provide me a screenshot of the Node Editor configuration using the tension node on a basic poly sphere?
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
 
 
--
---ОдноГлазы Jo---

**Comment by satcar77** [comment]
I am sorry, but I still can't understand. Can you please explain what the "deformed mesh", "original mesh","new mesh" are?

**Comment by satcar77** [comment]
Also, where can I get the tension map attribute in the new mesh as shown in your video

**Comment by satcar77** [comment]
I got it now. Thanks.

**Comment by rashxl** [comment]
Друзья, я заранее прошу прощения за то, что отвлекаю от дел. Просто очень важную тему хочу поднять. В кризисном положении находится ҏодной мне (по тётиной линии) Тёмочка. Ему всего десять лет. Он с обширными и глубокими ожогами сейчас без сознания пребывает...

Попробую рассказать, что произошло. Он с друзьями (всем по 10 лет) пошёл гулять. Как выяснилось - хулиганить. Хотели проверить, как горят такие вещества, как йод, антисептик, сахар, песок и прочая ерунда. Намешали - и вспыхнуло. Тёма отбежать не успел - вспыхнул и он. Повезло, что неподалёку были прохожие, которые и сумели справиться с пламенем.

Лицо отекло, веки набухли, вместо глаз — щелки. Сильнее всего пострадали шея, грудная клетка, левая рука, ноги. Скорая приехала быстро. Прибывшие на место медики сразу поставили капельницу и начали готовить к перевозке. Сказали, что у Тёмы глубокий ожог четвертой степени и 50-процентное поражение кожи, и что может умереть по дороге

Первые дни по прибытии в реанимацию, специалисты безостановочно обрабатывали раны и делали перевязки. С почками ситуация нормализовалась, а вот по зрению напротив положение ухудшилось (пока речи не идёт о его восстановлении). 25 октября его погрузили в состояние искусственного сна.

С тех пор Тёме провели уже две операции - удалили омертвевшие ткани. Постоянно обрабатывают пораженные участки, проводят комплексную терапию во избежание развития инфекции. Нужно готовить пересадку кожи (а ее не хватает). Нужно постоянно закупать специальные перевязочные материалы и лекарственные препараты. Они очень дорогие и не покрываются из средств ОМС. Плюс многоэтапное хирургическое лечение в течение длительного срока.

Даже когда стало ясно, что стоимость затрат переваливает за полтора миллиона рублей (причем, только на начальном этапе), то всё равно мы надеялись решить вопрос узким кругом. Но мы общими силами сумели найти только миллион, а время стало поджимать. 

Немного постеснявшись, мы все-таки решились придать огласку этой ситуации. Сложно рассчитывать на помощь со стороны. но вдруг кто-то проявит милосердие, понимание и чуткость (РосБанк: 4198-0451-0635-4086)

Кроме того, мы очень надеемся, что у кого-нибудь будут выходы на прессу, фонды, медицинских чиновников или врачей из этой сферы. Любой полезной информации будем очень и очень признательны.
